SYNONYMS = {
    "learn": ["study", "practice"],
    "learning": ["studying", "training"],
    "programming": ["coding", "development"],
    "code": ["programming", "software"],
    "job": ["career", "work"],
    "best": ["top", "recommended"],
    "good": ["best", "useful"],
    "difference": ["comparison", "compare"],
    "start": ["begin", "learn"],
    "language": ["programming"],
    "computer": ["technology", "software"],
    "business": ["company", "startup"],
    "money": ["finance", "income"],
    "health": ["medical", "wellness"],
    "phone": ["mobile", "smartphone"],
    "india": ["indian"],
    "usa": ["america", "american"],
    "retrieval": ["search", "ranking"],
    "information": ["data", "knowledge"],
    "engine": ["system", "machine"],
    "model": ["method", "approach", "technique"],
}
